[project]
name = "vpsctl"
version = "1.1.1"
description = "Set up a VPS with basic security and configuration"
homepage = "https://github.com/druagoon/vpsctl"
repository = "https://github.com/druagoon/vpsctl"
license = "MIT"
